export const VEHICLE_REPOSITORY_PROVIDER = 'VEHICLE_REPOSITORY_PROVIDER';
export const VEHICLE_SERVICE_PROVIDER = 'VEHICLE_SERVICE_PROVIDER';
export const VEHICLE_SERVICE_CONTAINER = 'VEHICLE_SERVICE_CONTAINER';
 